# Generated by Django 4.0.2 on 2022-02-21 18:15

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path=projects.models.images_path),
        ),
    ]
